grammar dk.sdu.mmmi.mdsd.Math with org.eclipse.xtext.common.Terminals

generate math "http://www.sdu.dk/mmmi/mdsd/Math"

Model:
	math+=MathExp*
;

MathExp:
	'var' name=ID '=' exp=Exp
;

Exp: PlusOrMinus;

Number:
	value=INT
;

PlusOrMinus returns Exp: MulOrDiv (
({Plus.left=current} '+' | {Minus.left=current} '-')
       right=MulOrDiv
     )* ;

MulOrDiv returns Exp: Primary (
({MulOrDiv.left=current} op=('*'|'/'))
       right=Primary
     )* ;

Primary:
	Number | '(' exp=Exp ')';