/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MathUiModule extends AbstractMathUiModule {

	public MathUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
