/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.ui.internal.MdsdActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MdsdActivator.getInstance().getInjector("dk.sdu.mmmi.mdsd.Math");
	}

}
