/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Use</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.VariableUse#getVariableUse <em>Variable Use</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getVariableUse()
 * @model
 * @generated
 */
public interface VariableUse extends Atomic
{
  /**
   * Returns the value of the '<em><b>Variable Use</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Use</em>' reference.
   * @see #setVariableUse(AbstractElement)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getVariableUse_VariableUse()
   * @model
   * @generated
   */
  AbstractElement getVariableUse();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.VariableUse#getVariableUse <em>Variable Use</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Use</em>' reference.
   * @see #getVariableUse()
   * @generated
   */
  void setVariableUse(AbstractElement value);

} // VariableUse
